month1=("january")
month2=("february")
month3=("march")
month4=("april")
month5=("may")
month6=("june")
month7=("july")
month8=("august")
month9=("september")
month10=("october")
month11=("november")
month12=("december")
month33=("error")
print(   "month 1:  "  + month1  )
print(   "month 2:  "  + month2  )
print(   "month 3:  "  + month3  )
print(   "month 4:  "  + month4  )
print(   "month 5:  "  + month5  )
print(   "month 6:  "  + month6  )
print(   "month 7:  "  + month7  )
print(   "month 8:  "  + month8  )
print(   "month 9:  "  + month9  )
print(   "month 10: "  + month10 )
print(   "month 11: "  + month11 )
print(   "month 12: "  + month12 )
print(   "month 33: "  + month33 )