name=(input("name-"))
yourage=(input("your age-"))
yourdob=(input("your dob-"))
yourlocation=(input("your location-"))
yourcollegename=(input("your clg name-"))
# print("name",name ,"yourage",yourage,"yourdob",yourdob,"yourlocation",yourlocation,"yourcollegename",yourcollegename)
print("hello","my name is ",name,".""i am ",yourage, "years old and was born on",yourdob,".""currntly,""iam located in",yourlocation,"and i completed my diploma at",yourcollegename")